version: '3.8'
services:
  # Service Backend (Golang) - Milik Raihan
  backend:
    image: raihanmzfr/chatbot_server:v1
    container_name: chatbot-backend
    environment:
      - GEMINI_API_KEY=AIzaSyARbUhIIPApg-LGxr7Q0O-tR0Dx4epfQ4M
      - GIN_MODE=release
    ports:
      - "8080:8080"
    restart: always
    networks:
      - chatbot-network

  # Service Frontend (Nginx/Web) - Milik Kawan
  frontend:
    # GANTI 'akun_kawan' dengan username asli kawanmu di Docker Hub
    image: arzana22/chatbot_client:v1 
    container_name: chatbot-frontend
    ports:
      - "80:80"        # Akses via browser di http://localhost
    depends_on:
      - backend
    restart: always
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge